# --- DDL for Metadata Logging ---

ETL_AUDIT_LOG_DDL = """
CREATE TABLE IF NOT EXISTS etl_audit_log (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id UUID NOT NULL,
    package_version VARCHAR(50) NOT NULL,
    load_mode VARCHAR(20),
    medgen_release_version VARCHAR(100), -- e.g., a release date or version number
    source_files JSONB, -- {'filename': '...', 'checksum': '...'}
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ,
    status VARCHAR(20) NOT NULL, -- In Progress, Succeeded, Failed
    records_extracted BIGINT,
    records_loaded BIGINT,
    error_count BIGINT,
    error_message TEXT
);
"""

# --- DDL for Staging Tables ---

STAGING_CONCEPTS_DDL = """
CREATE UNLOGGED TABLE IF NOT EXISTS staging_medgen_concepts (
    cui VARCHAR(10) NOT NULL,
    lat VARCHAR(3) NOT NULL,
    ts CHAR(1),
    lui VARCHAR(10) NOT NULL,
    stt VARCHAR(20),
    sui VARCHAR(10) NOT NULL,
    ispref CHAR(1),
    aui VARCHAR(10),
    saui VARCHAR(10),
    scui VARCHAR(50),
    sdui VARCHAR(50),
    sab VARCHAR(40) NOT NULL,
    tty VARCHAR(40) NOT NULL,
    code VARCHAR(50) NOT NULL,
    str TEXT NOT NULL,
    srl VARCHAR(10) NOT NULL,
    suppress CHAR(1) NOT NULL,
    cvf VARCHAR(50)
);
"""

STAGING_NAMES_DDL = """
CREATE UNLOGGED TABLE IF NOT EXISTS staging_medgen_names (
    cui VARCHAR(10) NOT NULL,
    name TEXT NOT NULL,
    source VARCHAR(40) NOT NULL,
    suppress CHAR(1) NOT NULL
);
"""
