# --- DDL for Metadata Logging ---

ETL_AUDIT_LOG_DDL = """
CREATE TABLE IF NOT EXISTS etl_audit_log (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id UUID NOT NULL,
    package_version VARCHAR(50) NOT NULL,
    load_mode VARCHAR(20),
    medgen_release_version VARCHAR(100), -- e.g., a release date or version number
    source_files JSONB, -- {'filename': '...', 'checksum': '...'}
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ,
    status VARCHAR(20) NOT NULL, -- In Progress, Succeeded, Failed
    records_extracted BIGINT,
    records_loaded BIGINT,
    error_count BIGINT,
    error_message TEXT
);
"""

# --- DDL for Staging Tables ---

STAGING_CONCEPTS_DDL = """
CREATE UNLOGGED TABLE IF NOT EXISTS staging_medgen_concepts (
    cui VARCHAR(10) NOT NULL,
    lat VARCHAR(3) NOT NULL,
    ts CHAR(1),
    lui VARCHAR(10) NOT NULL,
    stt VARCHAR(20),
    sui VARCHAR(10) NOT NULL,
    ispref CHAR(1),
    aui VARCHAR(10),
    saui VARCHAR(10),
    scui VARCHAR(50),
    sdui VARCHAR(50),
    sab VARCHAR(40) NOT NULL,
    tty VARCHAR(40) NOT NULL,
    code VARCHAR(50) NOT NULL,
    str TEXT NOT NULL,
    srl VARCHAR(10) NOT NULL,
    suppress CHAR(1) NOT NULL,
    cvf VARCHAR(50),
    raw_record TEXT
);
"""

# --- DDL for Semantic Types ---

STAGING_SEMANTIC_TYPES_DDL = """
CREATE UNLOGGED TABLE IF NOT EXISTS staging_medgen_semantic_types (
    cui VARCHAR(10) NOT NULL,
    tui VARCHAR(4) NOT NULL,
    stn VARCHAR(100),
    sty TEXT NOT NULL,
    atui VARCHAR(12),
    cvf VARCHAR(50),
    raw_record TEXT
);
"""

PRODUCTION_SEMANTIC_TYPES_DDL = """
CREATE TABLE IF NOT EXISTS {table_name} (
    semantic_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cui VARCHAR(10) NOT NULL,
    tui VARCHAR(4) NOT NULL,
    stn VARCHAR(100),
    sty TEXT NOT NULL,
    atui VARCHAR(12),
    cvf VARCHAR(50),
    is_active BOOLEAN NOT NULL DEFAULT true,
    last_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    raw_record TEXT
);
"""

PRODUCTION_SEMANTIC_TYPES_INDEXES_DDL = [
    "CREATE INDEX IF NOT EXISTS idx_{table_name}_cui ON {table_name} (cui);",
    "CREATE INDEX IF NOT EXISTS idx_{table_name}_tui ON {table_name} (tui);",
    "CREATE INDEX IF NOT EXISTS idx_{table_name}_is_active ON {table_name} (is_active);",
]

# --- DDL for Production Tables ---

# DDL for the main 'names' table in production.
# This table includes columns for soft-deletes and versioning.
PRODUCTION_NAMES_DDL = """
CREATE TABLE IF NOT EXISTS {table_name} (
    name_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cui VARCHAR(10) NOT NULL,
    name TEXT NOT NULL,
    source VARCHAR(40) NOT NULL,
    suppress CHAR(1) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    last_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    raw_record TEXT
);
"""

# DDL for indexes on the production 'names' table.
# These are created after data loading for better performance.
PRODUCTION_NAMES_INDEXES_DDL = [
    "CREATE INDEX IF NOT EXISTS idx_{table_name}_cui ON {table_name} (cui);",
    "CREATE INDEX IF NOT EXISTS idx_{table_name}_is_active ON {table_name} (is_active);",
]


# DDL for the main 'concepts' table in production.
PRODUCTION_CONCEPTS_DDL = """
CREATE TABLE IF NOT EXISTS {table_name} (
    concept_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cui VARCHAR(10) NOT NULL,
    lat VARCHAR(3) NOT NULL,
    ts CHAR(1),
    lui VARCHAR(10) NOT NULL,
    stt VARCHAR(20),
    sui VARCHAR(10) NOT NULL,
    ispref CHAR(1),
    aui VARCHAR(10),
    saui VARCHAR(10),
    scui VARCHAR(50),
    sdui VARCHAR(50),
    sab VARCHAR(40) NOT NULL,
    tty VARCHAR(40) NOT NULL,
    code VARCHAR(50) NOT NULL,
    str TEXT NOT NULL,
    srl VARCHAR(10) NOT NULL,
    suppress CHAR(1) NOT NULL,
    cvf VARCHAR(50),
    is_active BOOLEAN NOT NULL DEFAULT true,
    last_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    raw_record TEXT
);
"""

# DDL for indexes on the production 'concepts' table.
PRODUCTION_CONCEPTS_INDEXES_DDL = [
    "CREATE INDEX IF NOT EXISTS idx_{table_name}_cui ON {table_name} (cui);",
    "CREATE UNIQUE INDEX IF NOT EXISTS uidx_{table_name}_aui ON {table_name} (aui);",
    "CREATE INDEX IF NOT EXISTS idx_{table_name}_sab_code ON {table_name} (sab, code);",
    "CREATE INDEX IF NOT EXISTS idx_{table_name}_is_active ON {table_name} (is_active);",
]

STAGING_NAMES_DDL = """
CREATE UNLOGGED TABLE IF NOT EXISTS staging_medgen_names (
    cui VARCHAR(10) NOT NULL,
    name TEXT NOT NULL,
    source VARCHAR(40) NOT NULL,
    suppress CHAR(1) NOT NULL,
    raw_record TEXT
);
"""
