name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
        with:
          python-version: '3.11'
      - name: Run pre-commit hooks
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd

  test:
    name: Test
    needs: lint
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.11', '3.12']

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install -E test -E docs
        shell: bash

      - name: Run Unit Tests
        run: poetry run pytest tests/unit --cov=src --cov-report=xml:coverage-unit.xml
        shell: bash

      - name: Upload Unit Test Coverage
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage-unit.xml
          flags: ${{ matrix.os }}-py${{ matrix.python-version }}-unit
          fail_ci_if_error: true
          verbose: true

      - name: Run Integration Tests (Ubuntu only)
        if: runner.os == 'Linux'
        run: |
          # The AGENTS.md file noted a sudo requirement for local execution.
          # In GitHub Actions, the runner user has Docker permissions, so sudo is not needed.
          poetry run pytest tests/integration --cov=src --cov-report=xml:coverage-integration.xml
        shell: bash

      - name: Upload Integration Test Coverage (Ubuntu only)
        if: runner.os == 'Linux' && !cancelled()
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage-integration.xml
          flags: ${{ matrix.os }}-py${{ matrix.python-version }}-integration
          fail_ci_if_error: true
          verbose: true

      - name: Upload failure artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports-${{ matrix.os }}-py${{ matrix.python-version }}
          path: |
            coverage-unit.xml
            coverage-integration.xml
          if-no-files-found: ignore