name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      # Docker-in-Docker service is required for testcontainers
      dind:
        image: docker:dind
        # privileged is required for dind
        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: poetry install -E test -E docs

    - name: Run tests
      # Set DOCKER_HOST to connect to the dind service
      env:
        DOCKER_HOST: tcp://dind:2375
      run: poetry run pytest
